[package]
name = "jonswap"
version = "0.1.3"
edition = "2021"
description = "CLI for JONSWAP wave model."
license = "GPL-2.0-only"
readme = "readme.md"
repository = "https://github.com/haphaeu/jonswap_rs"

[dependencies]
rand = "0.8.5"
